# -*- coding: utf-8 -*-
"""MBTI_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/130FiC2l4Vm4fY2kCiHvtK_lLklxjve8p
"""

from google.colab import files
uploaded = files.upload()
file_path = list(uploaded.keys())[0]

import csv

def load_questions(file_path):
    # 先試 UTF-8
    try:
        f = open(file_path, "r", encoding="utf-8")
        reader = csv.DictReader(f)
        rows = list(reader)
        f.close()
    except UnicodeDecodeError:
        # 若失敗則改 Big5 / cp950
        f = open(file_path, "r", encoding="cp950")
        reader = csv.DictReader(f)
        rows = list(reader)
        f.close()

    questions = []
    for row in rows:
        questions.append([row["question"], row["dimension"], row["a"], row["b"]])
    return questions


def conduct_test(questions):
    scores = {"EI": 0, "SN": 0, "TF": 0, "JP": 0}

    for q in questions:
        question, dimension, option_a, option_b = q

        print("\n" + question)
        print("A.", option_a)
        print("B.", option_b)

        while True:
            answer = input("請輸入 A 或 B：").strip().upper()
            if answer in ["A", "B"]:
                break
            print("輸入錯誤，請輸入 A 或 B")

        if answer == "A":
            scores[dimension] += 1
        else:
            scores[dimension] -= 1

    return scores


def get_mbti(scores):
    result = ""
    result += "E" if scores["EI"] > 0 else "I"
    result += "S" if scores["SN"] > 0 else "N"
    result += "T" if scores["TF"] > 0 else "F"
    result += "J" if scores["JP"] > 0 else "P"
    return result


def main():
    questions = load_questions(file_path)

    print("歡迎來到 MBTI 心理測驗！請誠實作答。\n")

    scores = conduct_test(questions)
    result = get_mbti(scores)

    print("\n========================")
    print("你的 MBTI 結果是：", result)
    print("========================")


main()

# 直接在程式裡定義問題
questions = [
    {
        "question": "你在社交場合更喜歡？",
        "dimension": "EI",
        "a": "與多人互動",
        "b": "獨處或與少數人相處"
    },
    {
        "question": "你更依賴什麼來做決定？",
        "dimension": "TF",
        "a": "邏輯與分析",
        "b": "感受與價值觀"
    },
    {
        "question": "你處理事情時更傾向？",
        "dimension": "JP",
        "a": "按計畫行事",
        "b": "隨機應變"
    },
    {
        "question": "你偏好哪種資訊處理方式？",
        "dimension": "SN",
        "a": "實際經驗",
        "b": "直覺靈感"
    },
    {
        "question": "你做事時較像哪種人？",
        "dimension": "JP",
        "a": "喜歡提前安排計畫",
        "b": "喜歡保持彈性與自由"
    },
    {
        "question": "遇到問題時你傾向依賴什麼？",
        "dimension": "TF",
        "a": "客觀事實與邏輯",
        "b": "情緒與他人感受"
    },
    {
        "question": "你更容易從哪裡獲得能量？",
        "dimension": "EI",
        "a": "和人互動、聊天",
        "b": "自己獨處、思考"
    },
    {
        "question": "你學習新事物時偏好哪種方式？",
        "dimension": "SN",
        "a": "透過實作、具體例子",
        "b": "靠直覺與靈感理解"
    }
]


def conduct_test(questions):
    scores = {"EI": 0, "SN": 0, "TF": 0, "JP": 0}

    for q in questions:
        print("\n" + q["question"])
        print("A.", q["a"])
        print("B.", q["b"])

        while True:
            answer = input("請輸入 A 或 B：").strip().upper()
            if answer in ["A", "B"]:
                break
            print("輸入錯誤，請輸入 A 或 B")

        if answer == "A":
            scores[q["dimension"]] += 1
        else:
            scores[q["dimension"]] -= 1

    return scores


def get_mbti(scores):
    result = ""
    result += "E" if scores["EI"] > 0 else "I"
    result += "S" if scores["SN"] > 0 else "N"
    result += "T" if scores["TF"] > 0 else "F"
    result += "J" if scores["JP"] > 0 else "P"
    return result


def main():
    print("歡迎來到 MBTI 心理測驗！請誠實作答。\n")

    scores = conduct_test(questions)
    result = get_mbti(scores)

    print("\n========================")
    print("你的 MBTI 結果是：", result)
    print("========================")


main()